In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({
    "name":["Priyanka"],
    "age":[21]
})

In [5]:
df

       name  age
0  Priyanka   21

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

<h2>Series </h2>
<h4>It is one dimensional Labelled Array -
It has two components (values,index)</h4>

In [7]:
s = pd.Series([1,2,3,4,5])

print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
print(type(s))

<class 'pandas.core.series.Series'>

In [10]:
info ={
    "name":["Striver","Rohit Negi","Adity Tandon"],
    "package":["85lpa","2Cr","60lpa"]
}

df1 = pd.DataFrame(info)

In [11]:
df1

           name package
0       Striver   85lpa
1    Rohit Negi     2Cr
2  Adity Tandon   60lpa

In [14]:
#To access row
df1.index

RangeIndex(start=0, stop=3, step=1)

In [15]:
#To access columns
df1.columns

Index(['name', 'package'], dtype='object')

In [16]:

data = [["Priyanka","21"],["Nagnath","54"]]

df2 = pd.DataFrame(data,columns=["Name","Age"])

df2

       Name Age
0  Priyanka  21
1   Nagnath  54

<h2>DataFrame Methods</h2>

In [17]:
data2 = {
'Name': ['Aarav', 'Isha', 'Rohan', 'Sneha', 'Vikram'],
'Age': [25, 30, 35, 40, 45],
'City': ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Chennai']
}

df4 = pd.DataFrame(data2)

In [18]:
df4

     Name  Age       City
0   Aarav   25      Delhi
1    Isha   30     Mumbai
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai

In [20]:
#To list first n data
df4.head(6)

     Name  Age       City
0   Aarav   25      Delhi
1    Isha   30     Mumbai
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai

In [21]:
#To list last n data
df4.tail(3)

     Name  Age       City
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai

In [22]:
#To list random n samples
df4.sample(2)

    Name  Age       City
0  Aarav   25      Delhi
2  Rohan   35  Bangalore

In [23]:
#To list all columns
df4.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [24]:
#To list datatypes of all columns
df4.dtypes

Name    object
Age      int64
City    object
dtype: object

In [25]:
#To have stats info of numeric cols
df4.describe()

             Age
count   5.000000
mean   35.000000
std     7.905694
min    25.000000
25%    30.000000
50%    35.000000
75%    40.000000
max    45.000000

In [26]:
#To display col name, datatype and memory usage
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [27]:
#To display unique values count in each col
df4.nunique()

Name    5
Age     5
City    5
dtype: int64

In [ ]:
df4["City"] #Returns series

0        Delhi
1       Mumbai
2    Bangalore
3      Kolkata
4      Chennai
Name: City, dtype: object

In [ ]:
df4[["Name","City"]] #Return DF

     Name       City
0   Aarav      Delhi
1    Isha     Mumbai
2   Rohan  Bangalore
3   Sneha    Kolkata
4  Vikram    Chennai

In [31]:
df4[df4['Age'] > 30]

     Name  Age       City
2   Rohan   35  Bangalore
3   Sneha   40    Kolkata
4  Vikram   45    Chennai